"""empty message

Revision ID: c4c197056280
Revises: 37cd2a198646
Create Date: 2021-03-05 20:11:13.916070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c197056280'
down_revision = '37cd2a198646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'facebook_link')
    # ### end Alembic commands ###
